swagger: "2.0"
info:
  version: "0.0.1"
  title: "Amazon AWS EMR"
  description: "An OpenAPI Service to manage AWS EMR clusters."
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: ""
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /list_cluster:
    get:
      operationId: cloudmesh.emr.openapi.cloudmesh.emr.list_clusters
      description: "Returns the clusters visible to this account."
      parameters:
        - name: status
          description: "The status of the cluster to search for. [default: all]."
          in: query
          type: string
          required: false
      produces:
        - "application/json"
      responses:
        "200":
          description: "Cluster Listing"
          schema:
            $ref: "#/definitions/emr"
definitions:
  emr:
    type: "object"
    required:
      - "model"
    properties:
      model:
        type: "string"
